# Generated by Django 5.2.1 on 2025-10-26 01:43

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_content', markdownx.models.MarkdownxField(blank=True, verbose_name='Home Page Content')),
                ('about_content', markdownx.models.MarkdownxField(blank=True, verbose_name='About Page Content')),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
