# Generated by Django 6.0.1 on 2026-02-13 12:59

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0074_alter_bibliography_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('description', markdownx.models.MarkdownxField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('notes', markdownx.models.MarkdownxField(blank=True, default='')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('READING', 'Reading'), ('COMPLETE', 'Complete')], default='PLANNED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reading.readinglist')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_items', to='catalog.volume')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('reading_list', 'volume'), name='uniq_readinglistitem_list_volume')],
            },
        ),
    ]
