# Generated by Django 6.0.1 on 2026-02-14 00:37

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='global_notes',
            field=markdownx.models.MarkdownxField(blank=True, default=''),
        ),
    ]
