# Generated by Django 6.0.1 on 2026-02-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_readinglist_global_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinglist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
