# Generated by Django 6.0.1 on 2026-02-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_readinglist_options_alter_readinglist_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglist',
            old_name='global_notes',
            new_name='overview_notes',
        ),
    ]
