# Generated by Django 6.0.1 on 2026-02-14 12:16

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_alter_bibliography_options'),
        ('reading', '0004_rename_global_notes_readinglist_overview_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(blank=True, default='', max_length=200)),
                ('description', markdownx.models.MarkdownxField(blank=True, default='')),
                ('overview_notes', markdownx.models.MarkdownxField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReadingPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('notes', markdownx.models.MarkdownxField(blank=True, default='')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('READING', 'Reading'), ('COMPLETE', 'Complete')], default='PLANNED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.RemoveField(
            model_name='readinglist',
            name='owner',
        ),
        migrations.RemoveConstraint(
            model_name='readinglistitem',
            name='uniq_readinglistitem_list_volume',
        ),
        migrations.AddField(
            model_name='readingpath',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingpathitem',
            name='reading_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reading.readingpath'),
        ),
        migrations.AddField(
            model_name='readingpathitem',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_path_items', to='catalog.volume'),
        ),
        migrations.RemoveField(
            model_name='readinglistitem',
            name='reading_list',
        ),
        migrations.RemoveField(
            model_name='readinglistitem',
            name='volume',
        ),
        migrations.AddConstraint(
            model_name='readingpathitem',
            constraint=models.UniqueConstraint(fields=('reading_path', 'volume'), name='uniq_readingpathitem_list_volume'),
        ),
        migrations.DeleteModel(
            name='ReadingList',
        ),
        migrations.DeleteModel(
            name='ReadingListItem',
        ),
    ]
