# Generated by Django 6.0.1 on 2026-02-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_alter_bibliography_options'),
        ('reading', '0005_readingpath_readingpathitem_remove_readinglist_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingpath',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='readingpathitem',
            name='uniq_readingpathitem_list_volume',
        ),
        migrations.RemoveField(
            model_name='readingpath',
            name='theme',
        ),
        migrations.AddField(
            model_name='readingpathitem',
            name='locator',
            field=models.CharField(blank=True, default='', help_text='e.g., "Essay in The Monsters and the Critics", "pp. 109–161", "Ch. 3"', max_length=200),
        ),
        migrations.AddField(
            model_name='readingpathitem',
            name='source_volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reading_path_source_items', to='catalog.volume'),
        ),
        migrations.AddField(
            model_name='readingpathitem',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reading_path_items', to='catalog.work'),
        ),
        migrations.AddConstraint(
            model_name='readingpathitem',
            constraint=models.UniqueConstraint(fields=('reading_path', 'work'), name='uniq_readingpathitem_path_work'),
        ),
        migrations.AddConstraint(
            model_name='readingpathitem',
            constraint=models.UniqueConstraint(fields=('reading_path', 'position'), name='uniq_readingpathitem_path_position'),
        ),
        migrations.RemoveField(
            model_name='readingpathitem',
            name='volume',
        ),
    ]
