# Generated by Django 6.0.1 on 2026-02-14 13:17

import django.db.models.deletion
from django.db import migrations, models


def delete_null_work_items(apps, schema_editor):
    ReadingPathItem = apps.get_model("reading", "ReadingPathItem")
    ReadingPathItem.objects.filter(work__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_alter_bibliography_options'),
        ('reading', '0006_alter_readingpath_options_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_null_work_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='readingpathitem',
            name='work',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reading_path_items',
                to='catalog.work'
            ),
        ),
    ]
