# Generated by Django 5.2.1 on 2025-10-28 11:29

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dod', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('sort_name', models.CharField(blank=True, max_length=150, null=True)),
                ('match_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=255)),
                ('total_volumes', models.IntegerField(blank=True, null=True)),
                ('is_box_set', models.BooleanField(default=False)),
                ('notes', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_published', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='catalog.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('volume_number', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=200, null=True)),
                ('edition_notes', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('binding', models.CharField(blank=True, choices=[('HC', 'Hardcover'), ('PB', 'Paperback'), ('LI', 'Library Binding'), ('EB', 'Ebook'), ('OT', 'Other')], max_length=30, null=True)),
                ('condition', models.CharField(blank=True, choices=[('AN', 'As New'), ('FI', 'Fine'), ('NF', 'Near Fine'), ('VG', 'Very Good'), ('GO', 'Good'), ('FA', 'Fair'), ('RC', 'Reading Copy')], max_length=30, null=True)),
                ('dust_jacket', models.BooleanField(default=False)),
                ('dust_jacket_condition', models.CharField(blank=True, choices=[('AN', 'As New'), ('FI', 'Fine'), ('NF', 'Near Fine'), ('VG', 'Very Good'), ('GO', 'Good'), ('FA', 'Fair'), ('RC', 'Reading Copy')], max_length=30, null=True)),
                ('notes', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('book_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='catalog.bookset')),
                ('works', models.ManyToManyField(blank=True, related_name='volumes', to='catalog.work')),
            ],
            options={
                'ordering': ['book_set__title', 'volume_number', 'title'],
            },
        ),
    ]
