# Generated by Django 5.2.1 on 2025-10-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owned',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('CATALOG', 'Catalog'), ('INVENTORY', 'Inventory')], default='CATALOG', max_length=10),
            preserve_default=False,
        ),
    ]
