# Generated by Django 5.2.1 on 2025-10-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='isbn10',
            field=models.CharField(blank=True, help_text='10-digit ISBN (legacy, optional).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='isbn13',
            field=models.CharField(blank=True, help_text='13-digit ISBN (normalized).', max_length=13, null=True),
        ),
    ]
