# Generated by Django 5.2.1 on 2025-10-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sort_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Catalog', 'Catalog'), ('Inventory', 'Inventory')], default='Catalog', max_length=10),
        ),
    ]
