# Generated by Django 5.2.1 on 2025-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_owned_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Catalog', 'Catalog'), ('Inventory', 'Inventory'), ('Sold', 'Sold')], max_length=10),
        ),
    ]
