# Generated by Django 5.2.1 on 2025-10-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_sort_name_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='named_author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
