# Generated by Django 5.2.1 on 2025-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_volume_isbn10_volume_isbn13'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
