# Generated by Django 5.2.1 on 2025-10-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_named_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gutenburg_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookspotlight',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
