# Generated by Django 5.2.1 on 2025-10-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_volume_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='acquisition_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
