# Generated by Django 5.2.1 on 2025-10-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
