# Generated by Django 5.2.1 on 2025-10-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_gutenburg_info_bookspotlight_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookspotlight',
            name='bio',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
