# Generated by Django 5.2.1 on 2025-11-01 02:15

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_volume_acquisition_date_volume_acquisition_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('NOVEL', 'Novel'), ('NOVELLA', 'Novella'), ('SHORT_STORY', 'Short Story'), ('STORY_COLLECTION', 'Story Collection'), ('POEM', 'Poem'), ('POETRY_COLLECTION', 'Poetry Collection'), ('PLAY', 'Play / Drama'), ('ESSAY', 'Essay'), ('ESSAY_COLLECTION', 'Essay Collection'), ('NONFICTION_BOOK', 'Non-Fiction Book'), ('LETTER', 'Letter / Correspondence'), ('SPEECH', 'Speech / Lecture'), ('TRANSLATION', 'Translation'), ('ANTHOLOGY', 'Anthology / Edited Volume'), ('CRITICISM', 'Criticism / Commentary'), ('OTHER', 'Other')], default='NOVEL', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
