# Generated by Django 5.2.1 on 2025-10-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_acquisition_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='collectible_notes',
            new_name='collectibility_notes',
        ),
    ]
