# Generated by Django 5.2.1 on 2025-10-21 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_bookspotlight_bio_author_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.author')),
            ],
        ),
    ]
