# Generated by Django 5.2.1 on 2025-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_collectible_notes_book_collectibility_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_collectible',
        ),
        migrations.AddField(
            model_name='book',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Sold', 'Sold'), ('Donated', 'Donated'), ('Gifted', 'Gifted'), ('Discarded', 'Discarded')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='disposition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='recipient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Catalog', 'Catalog'), ('Inventory', 'Inventory')], max_length=10),
        ),
    ]
