# Generated by Django 5.2.1 on 2025-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_book_is_collectible_book_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shipping_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
