# Generated by Django 5.2.1 on 2025-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_authoralias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authoralias',
            options={'verbose_name_plural': 'aliases'},
        ),
        migrations.AddField(
            model_name='bookimage',
            name='small_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/thumbnails/'),
        ),
    ]
