# Generated by Django 5.2.1 on 2025-11-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_authoralias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='volume',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
