# Generated by Django 5.2.1 on 2025-10-22 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_authoralias_options_bookimage_small_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_images', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
