# Generated by Django 5.2.1 on 2025-11-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_volume_publication_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='volume',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
