# Generated by Django 5.2.1 on 2025-10-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_bookimage_author_alter_collection_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('author',), name='unique_image_per_author'),
        ),
    ]
