# Generated by Django 5.2.1 on 2025-11-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_volume_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
