# Generated by Django 5.2.1 on 2025-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_volume_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
