# Generated by Django 5.2.1 on 2025-10-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bookimage_unique_image_per_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_contributors',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
