# Generated by Django 5.2.1 on 2025-10-26 12:54

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_additional_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
