# Generated by Django 5.2.1 on 2025-11-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_volume_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='sort_title',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
