# Generated by Django 5.2.1 on 2025-11-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_volume_sort_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['sort_title']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['sort_title']},
        ),
        migrations.AddField(
            model_name='work',
            name='sort_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
