# Generated by Django 5.2.1 on 2025-11-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_volume_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
