# Generated by Django 5.2.1 on 2025-11-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_volume_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
