# Generated by Django 5.2.1 on 2025-11-04 13:40

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_collection_volume_volume_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
