# Generated by Django 5.2.1 on 2025-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_volume_collection_alter_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='sort_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
