# Generated by Django 5.2.1 on 2025-11-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_bookset_sort_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='collection',
        ),
        migrations.AddField(
            model_name='volume',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collections', to='catalog.collection'),
        ),
    ]
