# Generated by Django 5.2.1 on 2025-11-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_volume_collection_volume_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='volumes', to='catalog.collection'),
        ),
    ]
