# Generated by Django 5.2.1 on 2025-11-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_volume_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='volume_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Work'), ('COLLECTION', 'Collection of One Author'), ('ANTHOLOGY', 'Anthology (Multiple Authors)'), ('EDITED', 'Edited Edition'), ('COMMENTARY', 'Commentary or Critical Edition'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
