# Generated by Django 5.2.1 on 2025-11-09 23:25

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_volume_volume_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
