# Generated by Django 5.2.1 on 2025-11-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_genre_work_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='volume_url',
            field=models.URLField(blank=True, help_text='URL to ebook', null=True),
        ),
    ]
