# Generated by Django 5.2.1 on 2025-11-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_volume_volume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
