# Generated by Django 5.2.1 on 2025-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_author_author_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='volume_type',
        ),
        migrations.AddField(
            model_name='volume',
            name='volume_content_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Work'), ('COLLECTION_SINGLE_AUTHOR', 'Collection (One Author)'), ('ANTHOLOGY', 'Anthology (Multiple Authors)'), ('COMPOSITE', 'Composite / Edited Volume'), ('CRITICAL', 'Critical / Commentary Edition'), ('REFERENCE', 'Reference Work'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='volume_edition_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Edition'), ('COLLECTOR', "Collector's Edition"), ('DELUXE', 'Deluxe Edition'), ('ILLUSTRATED', 'Illustrated Edition'), ('FACSIMILE', 'Facsimile Edition'), ('REVISED', 'Revised Edition'), ('LIMITED', 'Limited Edition'), ('TEXTBOOK', 'Textbook / Academic Edition'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(blank=True, choices=[('NOVEL', 'Novel'), ('NOVELLA', 'Novella'), ('SHORT_STORY', 'Short Story'), ('STORY_CYCLE', 'Story Cycle'), ('POEM', 'Poem'), ('POETRY_COLLECTION', 'Poetry Collection'), ('PLAY', 'Play / Drama'), ('ESSAY', 'Essay'), ('ESSAY_COLLECTION', 'Essay Collection'), ('NONFICTION', 'Non-Fiction Work'), ('TRANSLATION', 'Translation'), ('COMPOSITE', 'Composite / Edited Work'), ('ANTHOLOGY', 'Anthology (Multiple Authors)'), ('CRITICISM', 'Criticism / Commentary'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
