# Generated by Django 5.2.1 on 2025-11-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_volume_volume_type_volume_volume_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(blank=True, choices=[('NOVEL', 'Novel'), ('NOVELLA', 'Novella'), ('SHORT_STORY', 'Short Story'), ('STORY_CYCLE', 'Story Cycle'), ('POEM', 'Poem'), ('POETRY_COLLECTION', 'Poetry Collection'), ('PLAY', 'Play / Drama'), ('ESSAY', 'Essay'), ('ESSAY_COLLECTION', 'Essay Collection'), ('NONFICTION', 'Non-Fiction Work'), ('TRANSLATION', 'Translation'), ('COMPOSITE', 'Composite / Edited Work'), ('ANTHOLOGY', 'Anthology (Multiple Authors)'), ('CRITICISM', 'Criticism / Commentary'), ('REFERENCE_WORK', 'Reference Work'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
