# Generated by Django 5.2.1 on 2025-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_work_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='volume_edition_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Edition'), ('COLLECTOR', "Collector's Edition"), ('DELUXE', 'Deluxe Edition'), ('ILLUSTRATED', 'Illustrated Edition'), ('FACSIMILE', 'Facsimile Edition'), ('REVISED', 'Revised Edition'), ('LIMITED', 'Limited Edition'), ('TEXTBOOK', 'Textbook / Academic Edition'), ('TRANSLATION', 'Translation'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
