# Generated by Django 5.2.1 on 2025-11-25 01:55

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_volume_volume_edition_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['sort_name']},
        ),
        migrations.AddField(
            model_name='bookset',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
