# Generated by Django 5.2.1 on 2025-12-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_volume_volume_edition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookset',
            name='isbn10',
            field=models.CharField(blank=True, help_text='10-digit ISBN (legacy, optional).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookset',
            name='isbn13',
            field=models.CharField(blank=True, help_text='13-digit ISBN (normalized).', max_length=13, null=True),
        ),
    ]
