# Generated by Django 5.2.1 on 2025-12-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_bookset_cover_url_bookset_isbn10_bookset_isbn13'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of acquisition (e.g. taxes, shipping', max_digits=10, null=True),
        ),
    ]
