# Generated by Django 5.2.1 on 2025-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_volume_acquisition_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
