# Generated by Django 5.2.1 on 2025-12-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_volume_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost of acquisition (e.g. taxes, shipping', max_digits=10, null=True),
        ),
    ]
