# Generated by Django 5.2.1 on 2025-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_volume_acquisition_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
