# Generated by Django 5.2.1 on 2025-12-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_bookset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookset',
            name='acquisition_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookset',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
