# Generated by Django 5.2.1 on 2025-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_bookset_acquisition_date_bookset_acquisition_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookset',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
