# Generated by Django 5.2.1 on 2025-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_volume_volume_edition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='boxset_case_condition',
            field=models.CharField(blank=True, choices=[('AN', 'As New'), ('FI', 'Fine'), ('NF', 'Near Fine'), ('VG', 'Very Good'), ('GO', 'Good'), ('FA', 'Fair'), ('RC', 'Reading Copy')], max_length=50, null=True),
        ),
    ]
