# Generated by Django 5.2.1 on 2025-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_alter_volume_volume_edition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
