# Generated by Django 5.2.1 on 2025-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_volume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
