# Generated by Django 5.2.1 on 2025-12-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
