# Generated by Django 5.2.1 on 2025-12-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_bookset_slug_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
