# Generated by Django 5.2.1 on 2025-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_work_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='volume',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Sold', 'Sold'), ('Donated', 'Donated'), ('Gifted', 'Gifted'), ('Discarded', 'Discarded')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='disposition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='recipient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='shipping_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='status',
            field=models.CharField(blank=True, choices=[('Catalog', 'Catalog'), ('Inventory', 'Inventory')], default='Catalog', max_length=30, null=True),
        ),
    ]
