# Generated by Django 5.2.1 on 2025-12-10 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_remove_volume_total_cost_volume_disposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(blank=True, max_length=200, null=True)),
                ('edition', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeBibliographyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_detail', models.CharField(blank=True, help_text='e.g. page 56, entry A2b, plate VIII, etc.', max_length=255, null=True)),
                ('bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bibliography')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliography_refs', to='catalog.volume')),
            ],
            options={
                'unique_together': {('volume', 'bibliography', 'reference_detail')},
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='bibliographies',
            field=models.ManyToManyField(related_name='volumes', through='catalog.VolumeBibliographyReference', to='catalog.bibliography'),
        ),
    ]
