# Generated by Django 5.2.1 on 2025-12-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_bibliography_volumebibliographyreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='bibliographies',
            field=models.ManyToManyField(blank=True, related_name='volumes', through='catalog.VolumeBibliographyReference', to='catalog.bibliography'),
        ),
    ]
