# Generated by Django 5.2.1 on 2025-12-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_alter_volume_bibliographies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='volume_edition_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Edition'), ('COLLECTOR', "Collector's Edition"), ('DELUXE', 'Deluxe Edition'), ('ILLUSTRATED', 'Illustrated Edition'), ('FACSIMILE', 'Facsimile Edition'), ('REVISED', 'Revised Edition'), ('LIMITED', 'Limited Edition'), ('BOOK_CLUB', 'Book Club'), ('SLIPCASED', 'Slipcased Edition'), ('TEXTBOOK', 'Textbook / Academic Edition'), ('POCKET', 'Pocket Edition'), ('TRANSLATION', 'Translation'), ('MUSIC', 'Music Notation with Lyrics'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(blank=True, choices=[('NOVEL', 'Novel'), ('NOVELLA', 'Novella'), ('SHORT_STORY', 'Short Story'), ('STORY_CYCLE', 'Story Cycle'), ('POEM', 'Poem'), ('POETRY_COLLECTION', 'Poetry Collection'), ('PLAY', 'Play / Drama'), ('ESSAY', 'Essay'), ('ESSAY_COLLECTION', 'Essay Collection'), ('NONFICTION', 'Non-Fiction Work'), ('TRANSLATION', 'Translation'), ('COMPOSITE', 'Composite / Edited Work'), ('ANTHOLOGY', 'Anthology (Multiple Authors)'), ('CRITICISM', 'Criticism / Commentary'), ('SONG_CYCLE', 'Song Cycle'), ('REFERENCE_WORK', 'Reference Work'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
