# Generated by Django 5.2.1 on 2025-12-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_alter_volume_volume_edition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='ex_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volume',
            name='ex_library_condition',
            field=models.CharField(default=False),
            preserve_default=False,
        ),
    ]
