# Generated by Django 5.2.1 on 2025-12-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_volume_ex_library_volume_ex_library_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='ex_library_condition',
        ),
    ]
