# Generated by Django 5.2.1 on 2025-12-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_remove_volume_ex_library_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
