# Generated by Django 5.2.1 on 2026-01-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_volume_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='sort_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
