# Generated by Django 5.2.1 on 2026-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_alter_volume_title_alter_work_sort_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='volume_url',
        ),
        migrations.AddField(
            model_name='work',
            name='work_ebook_url',
            field=models.URLField(blank=True, help_text='URL to ebook', null=True),
        ),
    ]
