# Generated by Django 6.0.1 on 2026-01-10 02:07

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_remove_volume_volume_url_work_work_ebook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COVER', 'Cover'), ('COPYRIGHT', 'Copyright page'), ('TITLE', 'Title page'), ('SPINE', 'Spine'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image_thumb', models.ImageField(upload_to=catalog.models.volume_image_upload_to)),
                ('image_display', models.ImageField(upload_to=catalog.models.volume_image_upload_to)),
                ('image_detail', models.ImageField(upload_to=catalog.models.volume_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.volume')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.volumeimage'),
        ),
    ]
