# Generated by Django 6.0.1 on 2026-01-11 02:48

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_volumeimage_volume_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COVER', 'Cover'), ('LEFT', 'Left'), ('SPINE', 'Spine'), ('RIGHT', 'Right'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image_thumb', models.ImageField(upload_to=catalog.models.bookset_image_upload_to)),
                ('image_display', models.ImageField(upload_to=catalog.models.bookset_image_upload_to)),
                ('image_detail', models.ImageField(upload_to=catalog.models.bookset_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.bookset')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
