# Generated by Django 6.0.1 on 2026-01-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_booksetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookset',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.booksetimage'),
        ),
    ]
