# Generated by Django 6.0.1 on 2026-01-13 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_bookset_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='primary_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_volumes', to='catalog.work'),
        ),
    ]
