# Generated by Django 6.0.1 on 2026-01-14 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_devnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devnote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
