# Generated by Django 6.0.1 on 2026-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_alter_devnote_notes_alter_devnote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devnote',
            name='referring_url',
            field=models.URLField(blank=True),
        ),
    ]
