# Generated by Django 6.0.1 on 2026-01-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_devnote_referring_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devnote',
            old_name='notes',
            new_name='note',
        ),
    ]
