# Generated by Django 6.0.1 on 2026-01-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_rename_notes_devnote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='devnote',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
