# Generated by Django 6.0.1 on 2026-01-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_devnote_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devnote',
            options={'ordering': ['-created_at']},
        ),
    ]
