# Generated by Django 6.0.1 on 2026-01-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_alter_devnote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devnote',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='devnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
