# Generated by Django 6.0.1 on 2026-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_alter_devnote_options_devnote_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
