# Generated by Django 6.0.1 on 2026-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_alter_devnote_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devnote',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
