# Generated by Django 6.0.1 on 2026-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_alter_devnote_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devnote',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='collection',
            name='scope',
            field=models.CharField(choices=[('VOLUME', 'Volumes only'), ('WORK', 'Works only'), ('BOTH', 'Works and Volumes')], default='VOLUME', max_length=20),
        ),
    ]
