# Generated by Django 6.0.1 on 2026-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_alter_devnote_options_collection_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='works', to='catalog.collection'),
        ),
    ]
