# Generated by Django 6.0.1 on 2026-01-29 02:52

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0069_work_collection'),
    ]

    operations = [
        # 1. Rename Collection → Bookshelf (NO DATA LOSS)
        migrations.RenameModel(
            old_name='Collection',
            new_name='Bookshelf',
        ),

        # 2. Remove Work.collection (since Work now uses collections differently)
        migrations.RemoveField(
            model_name='work',
            name='collection',
        ),

        # 3. Rename Volume.collection → Volume.bookshelves
        migrations.RenameField(
            model_name='volume',
            old_name='collection',
            new_name='bookshelves',
        ),
    ]

