# Generated by Django 6.0.1 on 2026-01-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_bookshelf_remove_work_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='bookshelves',
        ),
        migrations.AddField(
            model_name='volume',
            name='bookshelf',
            field=models.ManyToManyField(blank=True, related_name='volumes', to='catalog.bookshelf'),
        ),
    ]
