# Generated by Django 6.0.1 on 2026-01-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_remove_bookshelf_scope_remove_volume_bookshelves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='bookshelf',
            new_name='bookshelves',
        ),
    ]
