# Generated by Django 6.0.1 on 2026-01-29 13:20

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0072_rename_bookshelf_volume_bookshelves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name_plural': 'Bookshelves'},
        ),
        migrations.AddField(
            model_name='work',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='works', to='catalog.collection'),
        ),
    ]
