# Generated by Django 6.0.1 on 2026-02-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_collection_alter_bookshelf_options_work_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'verbose_name_plural': 'Bibliographies'},
        ),
    ]
