# Generated by Django 6.0.1 on 2026-02-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_alter_bibliography_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator', models.CharField(blank=True, default='', help_text='e.g., "pp. 109–161", "xiii–xxv", "Ch. 3", "Essay 5"', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='catalog.volume')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_entries', to='catalog.work')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('volume', 'work'), name='uniq_volumework_volume_work')],
            },
        ),
    ]
