# Generated by Django 6.0.1 on 2026-02-16 15:35

from django.db import migrations

def backfill_volumework(apps, schema_editor):
    Volume = apps.get_model("catalog", "Volume")
    VolumeWork = apps.get_model("catalog", "VolumeWork")

    Through = Volume.works.through

    for rel in Through.objects.all().iterator():
        VolumeWork.objects.get_or_create(
            volume_id=rel.volume_id,
            work_id=rel.work_id,
            defaults={"locator": "", "position": 0},
        )

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_volumework'),
    ]

    operations = [
        migrations.RunPython(backfill_volumework, migrations.RunPython.noop),
    ]
